# Generated by Django 4.2.16 on 2024-12-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_flight_airline"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="booked_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
